server:
  port: 8080
  servlet:
    application-display-name: Sample Web POS Service API

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_web_pos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false